# Common
obj-$(CONFIG_FSL_DPA)				+= dpaa_resource.o

# BMan
obj-$(CONFIG_FSL_BMAN)                          += bman.o bman_utils.o
obj-$(CONFIG_FSL_BMAN_PORTAL)                   += bman_portal.o bman_utils.o bman_api.o
obj-$(CONFIG_FSL_BMAN_DEBUGFS)                  += bman_debugfs.o
